# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db19.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='db19.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ndb19.proto\x12\x05proto\"C\n\x06Report\x12\x11\n\tauthority\x18\x01 \x01(\x0c\x12&\n\x07reports\x18\x02 \x03(\x0b\x32\x15.proto.TimestampedTEK\"*\n\rGetKeyRequest\x12\x0b\n\x03HAK\x18\x01 \x01(\x0c\x12\x0c\n\x04\x45NIN\x18\x02 \x01(\r\"\"\n\x11\x41\x64\x64ReportResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"O\n\x17GetDiagnosisKeyResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12%\n\x06record\x18\x02 \x01(\x0b\x32\x15.proto.TimestampedTEK\"+\n\x0eTimestampedTEK\x12\x0b\n\x03TEK\x18\x01 \x01(\x0c\x12\x0c\n\x04\x45NIN\x18\x02 \x01(\r2\x93\x01\n\x0b\x44iagnosisDB\x12\x36\n\tAddReport\x12\r.proto.Report\x1a\x18.proto.AddReportResponse\"\x00\x12L\n\x10GetDiagnosisKeys\x12\x14.proto.GetKeyRequest\x1a\x1e.proto.GetDiagnosisKeyResponse\"\x00\x30\x01\x62\x06proto3'
)




_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='proto.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authority', full_name='proto.Report.authority', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reports', full_name='proto.Report.reports', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=88,
)


_GETKEYREQUEST = _descriptor.Descriptor(
  name='GetKeyRequest',
  full_name='proto.GetKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='HAK', full_name='proto.GetKeyRequest.HAK', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ENIN', full_name='proto.GetKeyRequest.ENIN', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=132,
)


_ADDREPORTRESPONSE = _descriptor.Descriptor(
  name='AddReportResponse',
  full_name='proto.AddReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.AddReportResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=168,
)


_GETDIAGNOSISKEYRESPONSE = _descriptor.Descriptor(
  name='GetDiagnosisKeyResponse',
  full_name='proto.GetDiagnosisKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.GetDiagnosisKeyResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record', full_name='proto.GetDiagnosisKeyResponse.record', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=249,
)


_TIMESTAMPEDTEK = _descriptor.Descriptor(
  name='TimestampedTEK',
  full_name='proto.TimestampedTEK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TEK', full_name='proto.TimestampedTEK.TEK', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ENIN', full_name='proto.TimestampedTEK.ENIN', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=294,
)

_REPORT.fields_by_name['reports'].message_type = _TIMESTAMPEDTEK
_GETDIAGNOSISKEYRESPONSE.fields_by_name['record'].message_type = _TIMESTAMPEDTEK
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.message_types_by_name['GetKeyRequest'] = _GETKEYREQUEST
DESCRIPTOR.message_types_by_name['AddReportResponse'] = _ADDREPORTRESPONSE
DESCRIPTOR.message_types_by_name['GetDiagnosisKeyResponse'] = _GETDIAGNOSISKEYRESPONSE
DESCRIPTOR.message_types_by_name['TimestampedTEK'] = _TIMESTAMPEDTEK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), {
  'DESCRIPTOR' : _REPORT,
  '__module__' : 'db19_pb2'
  # @@protoc_insertion_point(class_scope:proto.Report)
  })
_sym_db.RegisterMessage(Report)

GetKeyRequest = _reflection.GeneratedProtocolMessageType('GetKeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETKEYREQUEST,
  '__module__' : 'db19_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetKeyRequest)
  })
_sym_db.RegisterMessage(GetKeyRequest)

AddReportResponse = _reflection.GeneratedProtocolMessageType('AddReportResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPORTRESPONSE,
  '__module__' : 'db19_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddReportResponse)
  })
_sym_db.RegisterMessage(AddReportResponse)

GetDiagnosisKeyResponse = _reflection.GeneratedProtocolMessageType('GetDiagnosisKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDIAGNOSISKEYRESPONSE,
  '__module__' : 'db19_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetDiagnosisKeyResponse)
  })
_sym_db.RegisterMessage(GetDiagnosisKeyResponse)

TimestampedTEK = _reflection.GeneratedProtocolMessageType('TimestampedTEK', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMPEDTEK,
  '__module__' : 'db19_pb2'
  # @@protoc_insertion_point(class_scope:proto.TimestampedTEK)
  })
_sym_db.RegisterMessage(TimestampedTEK)



_DIAGNOSISDB = _descriptor.ServiceDescriptor(
  name='DiagnosisDB',
  full_name='proto.DiagnosisDB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=297,
  serialized_end=444,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddReport',
    full_name='proto.DiagnosisDB.AddReport',
    index=0,
    containing_service=None,
    input_type=_REPORT,
    output_type=_ADDREPORTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDiagnosisKeys',
    full_name='proto.DiagnosisDB.GetDiagnosisKeys',
    index=1,
    containing_service=None,
    input_type=_GETKEYREQUEST,
    output_type=_GETDIAGNOSISKEYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIAGNOSISDB)

DESCRIPTOR.services_by_name['DiagnosisDB'] = _DIAGNOSISDB

# @@protoc_insertion_point(module_scope)
