# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import db19_pb2 as db19__pb2


class DiagnosisDBStub(object):
    """import "google/api/annotations.proto";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddReport = channel.unary_unary(
                '/proto.DiagnosisDB/AddReport',
                request_serializer=db19__pb2.Report.SerializeToString,
                response_deserializer=db19__pb2.AddReportResponse.FromString,
                )
        self.GetDiagnosisKeys = channel.unary_stream(
                '/proto.DiagnosisDB/GetDiagnosisKeys',
                request_serializer=db19__pb2.GetKeyRequest.SerializeToString,
                response_deserializer=db19__pb2.GetDiagnosisKeyResponse.FromString,
                )


class DiagnosisDBServicer(object):
    """import "google/api/annotations.proto";

    """

    def AddReport(self, request, context):
        """option (google.api.http) = {
        post: "/v1/db19/add-report"
        body: "*"
        };
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiagnosisKeys(self, request, context):
        """option (google.api.http) = {
        post: "/v1/db19/get-diagnosis-keys"
        body: "*"
        };
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiagnosisDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddReport': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReport,
                    request_deserializer=db19__pb2.Report.FromString,
                    response_serializer=db19__pb2.AddReportResponse.SerializeToString,
            ),
            'GetDiagnosisKeys': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDiagnosisKeys,
                    request_deserializer=db19__pb2.GetKeyRequest.FromString,
                    response_serializer=db19__pb2.GetDiagnosisKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.DiagnosisDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiagnosisDB(object):
    """import "google/api/annotations.proto";

    """

    @staticmethod
    def AddReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.DiagnosisDB/AddReport',
            db19__pb2.Report.SerializeToString,
            db19__pb2.AddReportResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDiagnosisKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.DiagnosisDB/GetDiagnosisKeys',
            db19__pb2.GetKeyRequest.SerializeToString,
            db19__pb2.GetDiagnosisKeyResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
