version: '3'

services:
  diagnosis-db:
    build: "./diagnosis-db"
    ports:
      - "5434:5432"
  diagnosis-api:
    build: "./diagnosis-api"
    ports:
      - "5000:5000"
    depends_on:
      - diagnosis-db
